name: themotorwash
description: TheMotorWash Appilication.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.12+22

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  add_2_calendar: ^2.1.2
  another_flushbar: ^1.10.28
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dotted_border: ^2.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  expandable_text: ^2.2.0
  firebase_analytics: ^9.1.0
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.3
  firebase_messaging: ^10.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_displaymode: ^0.3.2
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^5.0.0+4
  flutter_map: ^0.13.1
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^4.2.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_uxcam: ^2.0.1
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.7.0
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.9
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  in_app_update: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  lazy_load_scrollview: ^1.3.0
  location: ^4.3.0
  logger: ^1.0.0
  map_launcher: ^2.1.1
  path_provider: ^2.0.2
  paytm_allinonesdk: ^1.1.4
  photo_view: ^0.13.0
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  razorpay_flutter: ^1.2.9
  responsive_framework: ^0.1.4
  rive: ^0.7.28
  rounded_loading_button: ^2.0.9
  rxdart: ^0.27.1
  shimmer: ^2.0.0
  simple_fontellico_progress_dialog: ^0.2.0
  smooth_page_indicator: ^1.0.0+2
  upgrader: ^3.12.1
  url_launcher: ^6.0.12

dev_dependencies:
  build_runner: ^2.0.5
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - android/app/src/main/res/raw/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
